### ISSUE TITLE
Phaetus_bms6_front and Phaetus_bms7_front is the same STL.

### ISSUE THREAD

**Issue by JuicedEagle** [VoronDesign/Voron-Stealthburner#1]
I have looked through the Phaetus BMS files, and when i open the front part stl file for bms 7 it is the BMS6 inscription on it. 

and there is no visible difference between bms6_front and bms7_front.

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/9
fixed
