### ISSUE TITLE
Update 14h ago accidentally removed shroud

### ISSUE THREAD

**Issue by Marshalldog** [VoronDesign/Voron-Stealthburner#100]
hey
"[[a]_stealthburner_main_body.stl](https://github.com/VoronDesign/Voron-Stealthburner/blob/main/STLs/Stealthburner/%5Ba%5D_stealthburner_main_body.stl)" is incorrect, there's now no cooling shroud

**Comment by Anollya** [comment]
... and the STLs\Clockwork2\Direct_Drive\main_body.stl is the old one?  [a]_stealthburner_main_body.stl is the new main_body.stl?
What are the difference in the new release? Chancelog?

**Comment by Marshalldog** [comment]
the shroud was replaced with a clockwork 2 part

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/101
fixed
