### ISSUE TITLE
Filename change on manual pdf breaks link on vorondesign.com

### ISSUE THREAD

**Issue by akonkol** [VoronDesign/Voron-Stealthburner#103]
hey folks! broken manual link on https://vorondesign.com/voron_stealthburner for the manual:
it links to: https://github.com/VoronDesign/Voron-Stealthburner/raw/main/Manual/Assembly_Manual_SB.pdf
and I think it should link to https://github.com/VoronDesign/Voron-Stealthburner/blob/main/Manual/Assembly_Manual_SB_High_Contrast_7-7-23.pdf
Which was caused by a filename change introduced in https://github.com/VoronDesign/Voron-Stealthburner/commit/a3366cfdb4ab51f14771ab681128a3d72f70b06f

**Comment by nemgrea** [comment]
this should fix it https://github.com/VoronDesign/Voron-Stealthburner/pull/104
