### ISSUE TITLE
Additional missing files

### ISSUE THREAD

**Issue by VoronManiac** [VoronDesign/Voron-Stealthburner#108]
I went to print a replacement part but directory STLs/X_Carriage I see from earlier this year (3/11/2023) appears to be missing? or did it get moved?

**Comment by lexyan** [comment]
X_carriage has been moved to Voron-2/Trident/Voron-0..... repositories

**Comment by thetic** [comment]
switchwire is missing the carriage stls

**Comment by nemgrea** [comment]
> switchwire is missing the carriage stls

no they arent.
![image](https://github.com/VoronDesign/Voron-Stealthburner/assets/52015997/61b77600-cb46-44d6-b78e-76f13a457cf1)

**Comment by thetic** [comment]
You're right. I didn't think to find them in the gantry directories.
