### ISSUE TITLE
Klipper macros

### ISSUE THREAD

**Issue by jtdowney** [VoronDesign/Voron-Stealthburner#13]
The repo is missing the klipper_macros folder from the beta, which has the config you'd need for the LEDs.

**Comment by Grafton1046** [comment]
here's a link to the beta one
https://github.com/VoronDesign/Voron-Afterburner/blob/sb-beta/Klipper_Macros/stealthburner_leds.cfg

**Comment by jtdowney** [comment]
@Grafton1046 This issue is to point out that that needs to be copied here.

**Comment by nemgrea** [comment]
addressed
https://github.com/VoronDesign/Voron-Stealthburner/pull/15
