### ISSUE TITLE
Missing main body CAD

### ISSUE THREAD

**Issue by Garethgb** [VoronDesign/Voron-Stealthburner#131]
CAD files for all printheads and CW2 but cant find the main body CAD, only STL.

**Comment by Bunny350** [comment]
Hi there,
It should be available in Stealthburner repository. If you need them, you can [click here](https://github.com/VoronDesign/Voron-Stealthburner/tree/main/CAD).

**Comment by Garethgb** [comment]
> Hi there, It should be available in Stealthburner repository. If you need them, you can [click here](https://github.com/VoronDesign/Voron-Stealthburner/tree/main/CAD). _Proud owner and modder of two Voron printers._

Thanks. I was looking for it to be listed separately like the other parts but found it as the complete unit step file which is fine for what I need.
