### ISSUE TITLE
dragonfly BMS 7 fin

### ISSUE THREAD

**Issue by elvin159** [VoronDesign/Voron-Stealthburner#14]
the dragonfly BMS 7fin file stealthburner_printhead_phaetus_bms7_front.stl has P-BMS6 imprinted on the toolhead STL pretty sure that should be P-BMS7 to avoid confusion.

**Comment by nemgrea** [comment]
![Capture](https://user-images.githubusercontent.com/52015997/181148743-b37da84e-b5c9-4885-8515-7664f5a1c060.PNG)
