### ISSUE TITLE
STEP File Inconsistencies 

### ISSUE THREAD

**Issue by ValuableToast** [VoronDesign/Voron-Stealthburner#16]
There are a few inconsistencies with the STEP files compared to some of the well established files like the 2.4

- SW X Carriage CW2 - There are no part names here just body 1, 2, 3 etc.
- CW2 - Not colored

As a suggestion, why not have them all in a single file like afterburner is setup. It makes seeing the fitment of the three parts easier.

Thank you for your tireless work on this!!

**Comment by wile-e1** [comment]
SW carriage has been fixed

Colors on CW2 have also been fixed.  There was some weird export issue from Inventor.  It took some digging but I got it solved.

PR incoming soon.
