### ISSUE TITLE
Incorrect Screw Length for ADXL345 mounts

### ISSUE THREAD

**Issue by Drachenkaetzchen** [VoronDesign/Voron-Stealthburner#17]
In the CAD, the two screws attaching the ADXL345 mount to the toolhead body are labelled as M3x16, but are in fact M3x12.

![image](https://user-images.githubusercontent.com/162974/181730640-0f4bfe96-789d-49b9-b8ad-15a142e87ef7.png)

The manual doesn't mention the two screws, but it might give issues with a BOM when it's based on the CAD screws

**Comment by wile-e1** [comment]
The issue has been corrected and a PR will be submitted shortly.
