### ISSUE TITLE
Wrong screws on manual for mounting fan housing to assembly.

### ISSUE THREAD

**Issue by lococnc** [VoronDesign/Voron-Stealthburner#20]
Too long a screw specified in manual.
Needs to be a M3x20 to attach the stealthburner upper screws, not M3x25

![image](https://user-images.githubusercontent.com/46273940/182040781-972a7c3a-145a-40a2-88de-bfeec6ec38e4.png)

**Comment by nemgrea** [comment]
This is not a mistake, 25mm screws are intentional as this allows the hotend to be dropped out without having to fully remove the front fan assembly
