### ISSUE TITLE
Cooling duct model error

### ISSUE THREAD

**Issue by BHoggs** [VoronDesign/Voron-Stealthburner#30]
There appears to be a rogue triangle in the cooling duct of the revo mount, it's causing extrusions in mid-air when trying to slice/print

![image](https://user-images.githubusercontent.com/40219783/185015851-74d3d17c-1488-4b2f-bdae-b8312f019605.png)

**Comment by BHoggs** [comment]
Actually on closer analysis, it appears to be present on all of the cooling duct versions. It's present in the CAD models so it doesn't appear to be an export error

![image](https://user-images.githubusercontent.com/40219783/185017617-75aab7c6-8eb7-4ef2-9132-d9609b760c68.png)

**Comment by wile-e1** [comment]
This has all been taken care of and will be updated shortly
