### ISSUE TITLE
Misnamed ADXL mounting bolts in CAD model

### ISSUE THREAD

**Issue by ForgeThrall** [VoronDesign/Voron-Stealthburner#34]
The mounting bolts for the ADXL are named as M3x16_SHCS_1 in [Stealthburner_Assembly.stp](https://github.com/VoronDesign/Voron-Stealthburner/blob/main/CAD/Stealthburner_Assembly.stp), but when measured they are actually 12mm long. Checking irl, 12mm is indeed the appropriate length. The bolt length is never stated in the manual.

**Comment by wile-e1** [comment]
This will be corrected in the next update.  Thank you.

Autodesk Inventor is giving me a ton of grief when exporting to STP files.
