### ISSUE TITLE
STL is wrong

### ISSUE THREAD

**Issue by cryd-s** [VoronDesign/Voron-Stealthburner#35]
STLs/X_Carriage/x_frame_V2TR_MGN12_left.stl

the passage for a screw is missing here it also affects the other side

**Comment by MaximeLambrechts** [comment]
Are you refering to the screws that mount the extruder to the carriage? These holes now accept heatset inserts and the extruder is now mounted from the front. Have a look at the manual :)

**Comment by cryd-s** [comment]
Ah ok - thats terrible for lgx users :(

**Comment by MaximeLambrechts** [comment]
This mount works well with the new carriage : https://www.thingiverse.com/thing:5242645
