### ISSUE TITLE
Incorrect quantity for M3x6 FHCS listed in BOM

### ISSUE THREAD

**Issue by jjkrygsman** [VoronDesign/Voron-Stealthburner#36]
According to the BOM, 2 x M3x6 FHCS are required.  But going through the manual I see that 3 are required, one on page 20 and two on page 56.

**Comment by nemgrea** [comment]
![Capture](https://user-images.githubusercontent.com/52015997/187289099-f4ddde76-ca71-457b-8856-2459a8ef4f59.PNG)
