### ISSUE TITLE
Wrong bolts length for tool cartridge in the manual

### ISSUE THREAD

**Issue by bistory** [VoronDesign/Voron-Stealthburner#37]
Hi,

I followed the manual, everything looks good except for one step for the tool catridge (page **41**).
The manual tells to use M3x12 bolts but they won't fit.
It should be M3x14 (tried that, it works) or M3x16 (didn't try that but it should work, based on CAD).

Thanks for the hard work !

**Comment by BerzerkaDurk** [comment]
I checked the toolhead models for all of the hotends, and the distance from the bottom of the counterbore to the opposite side of the rear mount is 10.5 mm on all of them, so a 12 mm screw should work fine.

Any chance your heatsets for those 2 screws are set below the surface of the front mount?

**Comment by BerzerkaDurk** [comment]
![image](https://user-images.githubusercontent.com/81716812/188354355-5b11cffa-e805-4f6c-a65e-86ff516f39c8.png)

**Comment by bistory** [comment]
> ![image](https://user-images.githubusercontent.com/81716812/188354355-5b11cffa-e805-4f6c-a65e-86ff516f39c8.png)

Thanks for your check but it's not the same hole ^^

<img width="468" alt="Capture d’écran 2022-09-05 à 07 33 45" src="https://user-images.githubusercontent.com/108102/188367590-ec611178-a9bc-4435-b685-deaf2bf9e302.png">

**Comment by BerzerkaDurk** [comment]
That _is_ the right hole. It's the only hole with the hardware on the page you mentioned. Page 41

The way you are measuring shows the max depth the screw can go.

The way I'm measuring shows how much of the screw extends past the rear half. If the counterbore is 10.5 mm from the other side of the rear part, a 12 mm screw will extend 1.5 mm past and into the heatset in the front part. It's pretty basic.

**Comment by bistory** [comment]
Ok strange then because my inserts are not 1.5mm below the surface...
I will check if my screws have the correct size

**Comment by BerzerkaDurk** [comment]
Probably wouldn't hurt to change them to 14s anyway. Rule of thumb is usually 1 diameter of thread engagement minimum, and 1.5 mm only gives you 1/2 of a diameter.

**Comment by wile-e1** [comment]
> Probably wouldn't hurt to change them to 14s anyway.
> 
> Rule of thumb is usually 1 diameter of thread engagement minimum, and 1.5 mm only gives you 1/2 of a diameter, plus you don't get a full thread all the way out to the end of the screw, further reducing engagement length.
> 
> Alternatively, the designers could, of course, keep the 12 mm screws and make the counterbores a bit deeper.

We won't be changing the bolt length to M3x14 because it is not a standard size in our Voron category of parts.

M3x12 work ok because the plastic under the head of the bolt compresses some when the screw is tightened.  
M3x16 also works because there is clearance on the other side of the insert to allow the screw to protrude past the heatset.


![image](https://user-images.githubusercontent.com/34219833/188903945-9d99365f-88ac-402e-9ee2-3fe3c15db8c9.png)

**Comment by bistory** [comment]
Thanks for your reply @wile-e1 , I have checked again M3x12, it fits, now that the counterbore holes have been "done" by longer screws. The screws measure 12mm with no extra, the printer is correctly calibrated. I had no problem with other screws.

I think M3x16 wouldn't hurt because those pieces are not meant to be disassembled regularly...

Here is some pictures of how it fits with M3x12 : 

![20220907_180952](https://user-images.githubusercontent.com/108102/188954253-6891eb12-9a5e-48ac-9c6e-ae79de3b9002.jpg)
![20220907_181003](https://user-images.githubusercontent.com/108102/188954267-a326c8ff-60a7-4b54-ae77-1a0511ce303b.jpg)
