### ISSUE TITLE
No extrusion or move

### ISSUE THREAD

**Issue by rainerschulte** [VoronDesign/Voron-Stealthburner#39]
On my Switchwire I had to replace my Afterburner and have a Stealthburner almost ready except for the Front.
I connected the LDO NEMA 14 to the Extruder but get no move on the inserted Filament. What coud it be?

**Comment by raymondh2** [comment]
Please try our Reddit page or Discord server for support. We use GitHub for managing design issues and support questions tend to go unanswered. https://vorondesign.com/ under community
