### ISSUE TITLE
Cutting Jig missing

### ISSUE THREAD

**Issue by mkevenaar** [VoronDesign/Voron-Stealthburner#4]
On page 55 of the documentation there is a mention of a cutting jig for the 5015 fan. 

I am unable to find it in the STLs folder. I can't find it either in the BETA repository.

**Comment by jtdowney** [comment]
I noticed that as well and came here to post. I believe it should be roughly the same as the 5015 deearing tool in https://github.com/VoronDesign/VoronUsers/tree/53778894972e58cf454b9c5ecdb856f19b2470c6/printer_mods/Badnoob/AB-BN/STL_files. That is what I've used for now.

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/10
Added
