### ISSUE TITLE
Stl filenames with the _SW suffix

### ISSUE THREAD

**Issue by StevensStuff** [VoronDesign/Voron-Stealthburner#43]
I've been noticing a lot of people asking questions on Discord what the _SW means in the file names.  For example STLs/Clockwork2/chain_anchor_2hole_SW.stl

Can we either change the suffix to _Switchwire and/or add that suffix to the Readme.md in the STLs/ folder for Filename Nomenclature?

**Comment by bythorsthunder** [comment]
I think this is a good idea. The SW acronym seems to be very confusing to newcomers who may not even be aware the Switchwire is a Voron printer.

**Comment by DT27** [comment]
> 

it's me! I have to search "SW" and "Switchwire" to find out that!
