### ISSUE TITLE
E3D V6 stringing

### ISSUE THREAD

**Issue by tekgamerpt** [VoronDesign/Voron-Stealthburner#49]
Hello
I've been testing stealthburner with a V6 mostly printing PLA. Already tweaked temperature, retraction, retraction speed, etc and still having problems with stringing.
It seems that air flow not going directly to the nozzle point direction.
Anyone with similar problems or am i missing something?

Cheers and keep up the good work

**Comment by raymondh2** [comment]
Please try for support on our community pages listed on vorondesign.com We use GitHub for keeping track of issues not troubleshooting help
