### ISSUE TITLE
X_Carriage don't have hall effect endstop

### ISSUE THREAD

**Issue by sad1ce** [VoronDesign/Voron-Stealthburner#53]
Default X_Carriage from Voron2.4/Trident have place for hall effect endstop, is it possible to add it to Stealthburner X_Carriage ?

**Comment by BerzerkaDurk** [comment]
The one I printed has one...
![20221028_120011](https://user-images.githubusercontent.com/81716812/198681855-3d9369ae-fad1-4a35-bdea-0594b01b2a4b.jpg)

**Comment by sad1ce** [comment]
Yes, i checked it. I thing SB manual should have explain this, like in Voron2.4/Trident manual.
Someone, who build Voron2.4/Trident with SB from scratch, will likely use SB manual for X_Carriage assembly, like i did ;) and will not notice reference to original manual.
