### ISSUE TITLE
Rename chain anchor to cable bridge or update documentation. 

### ISSUE THREAD

**Issue by aeiounix** [VoronDesign/Voron-Stealthburner#54]
Does this warrant a pull request? 

Page 31 of the assembly manual reference cable bridge. Tripped me up. If it's just me, close this issue. But if we think other people might stumble on this it's a simple fix, which is the real focus of this issue.

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/88
