### ISSUE TITLE
Undersized counterbore in Stealthburner_Printhead_Dragon TH front part 

### ISSUE THREAD

**Issue by BluePaci** [VoronDesign/Voron-Stealthburner#56]
![image](https://user-images.githubusercontent.com/56056849/200117859-672c322e-7a0f-4df4-b5db-92999a294740.png)

Should be at least 5.5mm for M3 SHCS (if anything, 6.0, to account for flattening at the top)

Regards, Blupaci

**Comment by BluePaci** [comment]
Was mistaken

**Comment by BerzerkaDurk** [comment]
Might have something to do with the fact that those holes are meant for M2.5 screws...
