### ISSUE TITLE
The stealthburner manual says to use M3 bolts when M2.5 bolts are correct

### ISSUE THREAD

**Issue by oernster** [VoronDesign/Voron-Stealthburner#58]
Page 42 of the stealthburner manual says to use M3x8 bolts.  a) the holes are not big enough and b) they do not fit a dragon high flow hotend.  Also, the dragon high flow hotend needs to have the top piece removed which is not mentioned in the manual at an earlier point in the manual.

For me, I heat setted M3x8 bolts and THEN discovered that the hotend didn't take the bolts and completely damaged the parts trying to heat remove them.  Now I've had to resource the parts and I've learned the hard way that M2.5x8 is ACTUALLY required.

Please can you address this in the manual.

**Comment by oernster** [comment]
OK, so let's clarify, perhaps the manual was accurate but perhaps the manual ought to indicate a dragon high flow as an option.  OR say careful the bolt sizes are only for the revo.

**Comment by BerzerkaDurk** [comment]
>  OR say careful the bolt sizes are only for the revo.
![image](https://user-images.githubusercontent.com/81716812/203488919-95298531-182b-4021-95e1-88c271edce98.png)

**Comment by Kosh42** [comment]
You heat what the bolts? 🤨

**Comment by raymondh2** [comment]
Manual already addresses other hotends needing other size bolts
