### ISSUE TITLE
Rapido Hotend Rear fit for Tap

### ISSUE THREAD

**Issue by Dr-Info** [VoronDesign/Voron-Stealthburner#59]
Discord user: Hagbard#7867 discovered an issue with the rapido_rear_cw1 and rapido_rear_cw2 mounting to Tap. The hotend couldn't sit flush due to the BHCS on TAP, see Link 1. Hagbard moded the rear mounts and pinned it in Voron_Tap, see Link 2.

Link 1: https://cdn.discordapp.com/attachments/1041007230239125574/1047294839181557800/unknown.png
Link 2: https://discord.com/channels/460117602945990666/1041007230239125574/1047298344680165466

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/74
