### ISSUE TITLE
E3D-V6 CAD

### ISSUE THREAD

**Issue by dabaiyyds** [VoronDesign/Voron-Stealthburner#61]
I need E3D-V6 air duct model CAD file, thank you!

**Comment by BerzerkaDurk** [comment]
CAD/Printheads/Stealthburner_Printhead_V6.stp ?

**Comment by dabaiyyds** [comment]
thanks, i found it



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月14日(星期三) 下午3:53
收件人: ***@***.***&gt;; 
抄送: "不爱@又何必@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [VoronDesign/Voron-Stealthburner] E3D-V6 CAD (Issue #61)





 
CAD/打印头/Stealthburner_Printhead_V6.stp ？
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您创作了该线程。消息 ID：<VoronDesign/Voron-Stealthburner/issues/61/1350573803 @ github 。com&gt;
