### ISSUE TITLE
the accent naming should be swapped with accent color

### ISSUE THREAD

**Issue by cnnblike** [VoronDesign/Voron-Stealthburner#64]
I just realized that the "[a]_stealthburner_main_body" of stealthburner is printed in accent color according to the naming schema, this makes the printed Stealthburner looks primarily in "accent" color (especially from the front view) - that make this naming bit confusing.

**Comment by raymondh2** [comment]
The front is an accent color. Base VS Accent naming is based on V2.4/Tridents Accent/Base scheme
