### ISSUE TITLE
CW2 guidler STL/STP mismatch

### ISSUE THREAD

**Issue by teookie** [VoronDesign/Voron-Stealthburner#67]
Geometry of guidler is different in STL file than in STP file. See photos below.

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/14007356/210155606-121025a7-4745-4e4f-8389-0f642ac39a9e.png">

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/14007356/210155628-63cfb09f-fcc4-4633-9d23-be6cefc5010f.png">

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/73
