### ISSUE TITLE
Incorrect screw length in X-Carriage

### ISSUE THREAD

**Issue by MapleLeafMakers** [VoronDesign/Voron-Stealthburner#7]
The M3x40 screw used to connect the 2 halves of the x-carriage should actually be an M3x30, M3x40 would stick out the other side:

![image](https://user-images.githubusercontent.com/105010153/180665908-de18ea53-befb-4e97-a4c8-b5dbe9e6b598.png)

The CAD also has this screw mis-labelled as M3x40 but it is in fact 30mm long.

![image](https://user-images.githubusercontent.com/105010153/180665931-e9cc4744-71dd-4729-9373-09d0a6ba6386.png)

**Comment by wile-e1** [comment]
The issue has been corrected.  PR to be submitted shortly.
