### ISSUE TITLE
[documentation] Mention access to 50t

### ISSUE THREAD

**Issue by boop5** [VoronDesign/Voron-Stealthburner#71]
Page 30 is about setting backlash.

It could be helpful to mention that you can actually access the 50t to test the backlash. That would never have occured to me when I built my first voron (first printer).

![image](https://user-images.githubusercontent.com/4655466/212442993-3d35fdd9-d121-4874-b949-e50664e3cf30.png)

On a side note: It'd be cool to get a link to a youtube video (or similar) like you do w/ the heat set insert QR code that maybe briefly explains what backlash is and how it should look like

![image](https://user-images.githubusercontent.com/4655466/212443099-200db364-2cd8-4b2b-b05d-5955c16c9c1d.png)

**Comment by neeamradia** [comment]
I agree completely, for people like me who have never worked with this kind of stuff before, this page was very confusing as it says 'slight play' but as I have never experienced this before, I didn't know how much play is required and 'slight' doesn't really help. Even 4-5 months after building the printer i have no idea!

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/88
