### ISSUE TITLE
[STL] Volcano + Voron Stealthburner

### ISSUE THREAD

**Issue by pasha4ur** [VoronDesign/Voron-Stealthburner#72]
Hello.

Please add volcano support. It is only a few millimeters longer than the standard V6 block.

I understand that the developers of the Voron are from rich countries and you are not very interested in people from less rich countries.

But the volcano is a cheap and productive solution. And V6 thermal barriers are a cheap consumable for printing with composites unlike dragons and other expensive solutions.

**Comment by BerzerkaDurk** [comment]
Wow. That's a pretty insulting assumption.

**Comment by pasha4ur** [comment]
> Especially given that they already included support for the standard V6 - the cheapest thing going.

I wrote about Volcano. They don't want to add it and wrote about this in their FAQ.

**Comment by BerzerkaDurk** [comment]
They have hundreds of hours into developing the design for 7 different hotends all over the price spectrum. You can't reasonably expect them to accommodate every person's particular requests.
You could always take the freely supplied CAD files and modify them to suit yourself.

**Comment by pasha4ur** [comment]
> They have hundreds of hours into developing the design for 7 different hotends all over the price spectrum. You can't reasonably expect them to accommodate every person's particular requests. You could always take the freely supplied CAD files and modify them to suit yourself.

II created a request not to you. Why are you breeding flood here? Do you have a boring life and have nothing else to do?


This man supports even more hotends and modules https://main.eva-3d.page/getting_started/

**Comment by BerzerkaDurk** [comment]
welp, i have no idea what "breeding flood" is supposed to mean, but if you are going to come on here and take a dump on the people who have spent untold amounts of their free time designing these things and freely giving away their time and energy to helping people around the world and accuse them of not caring about people from less fortunate countries merely for not wanting to spend hours and hours accommodating one person's request, then yeah, i'm gonna say something.

**Comment by BerzerkaDurk** [comment]
...and if you think that guy designs better printers and supports what you want to use, by all means go with his design. lol

**Comment by pasha4ur** [comment]
> ...and if you think that guy designs better printers and supports what you want to use, by all means go with his design. lol

It seems to me that you are nobody to give instructions to anyone.

I don't want to waste time talking to useless you.

**Comment by Lordinio** [comment]
[here](https://letmegooglethat.com/?q=stealthburner+volcano&l=1)

**Comment by Haxk20** [comment]
OK i will just ignore the incredibly toxic comments above and give you answer as if you didnt say them.

There are few reasons why Volcano and other super high flow hotends as super volcano and rapido ultra high flow is that they are far too long. In case of volcano and super volcano they are so long that the heatbreak has tendency to bend when the nozzle hits something.

The final nail in the coffin tho is that stealthburner has airflow optimized cooling path. If the team were to extend this the entire work put into optimizing this would have to be reworked. Which is in the good range of few hundred hours.
Nobody wants to do this. And if you simply just extend it you are loosing bunch of the efficiency.

+ volcano can be easily replaced by going Dragon HF with CHT nozzle. I understand the price point. 100euro is a LOT to pay for a hotend. But so is VORON itself. The printer itself is expensive. But you do get what you pay for it. An amazing hotend that will get at least 30mm/s^3 and with CHT even 40. So the price is very much justified. And the reasoning behind not doing volcano and etc support is solid. The CAD is there. You can always grab the cad and modify it yourself and spend the hundreds of hours badnoob spent himself on optimizing the flow.

**Comment by pasha4ur** [comment]
Not a super volcano is not long enough to have an impact.  It also has a narrower heatblock than the regular v6. This contributes to better blowing of the part.  I have one of those printers that comes with a volcano from the factory.

**Comment by nemgrea** [comment]
this isnt an issue its a feature request, thats not what github issue tracking is for. closing.

**Comment by KiloQubit** [comment]
@pasha4ur your replies in this thread are not in the spirit of being excellent to each other.  Be polite, do better.

As for your request, it has been answered, and we have no current plans to support the Volcano.  "not long enough to have an impact" is incorrect, the airflow is optimized to blow right at the tip of the nozzle, anything longer will need the ducts to be modified to move where the airflow hits.

**Comment by pasha4ur** [comment]
"Plus volcano can be easily replaced by going Dragon HF with CHT nozzle. I understand the price point. 100euro is a LOT to pay for a hotend."


And we will change these 2 components each time after 1-3 spools of hard composite materials?

**Comment by pasha4ur** [comment]
> @pasha4ur your replies in this thread are not in the spirit of being excellent to each other. Be polite, do better.
> 
> As for your request, it has been answered, and we have no current plans to support the Volcano. "not long enough to have an impact" is incorrect, the airflow is optimized to blow right at the tip of the nozzle, anything longer will need the ducts to be modified to move where the airflow hits.


Do you have any evidence of the short volcano problem?  For example, physical simulations.  You may have found problems that the huge staff of engineers with specialized education who work in e3d and other companies did not guess about.

**Comment by KiloQubit** [comment]
> > @pasha4ur your replies in this thread are not in the spirit of being excellent to each other. Be polite, do better.
> > As for your request, it has been answered, and we have no current plans to support the Volcano. "not long enough to have an impact" is incorrect, the airflow is optimized to blow right at the tip of the nozzle, anything longer will need the ducts to be modified to move where the airflow hits.
> 
> Do you have any evidence of the short volcano problem? For example, physical simulations. You may have found problems that the huge staff of engineers with specialized education who work in e3d and other companies did not guess about.

Extensive airflow simulations have been done to arrive at the current design, with airflow pointed exactly where the design has the nozzle.  Moving the nozzle lower will certainly impact it.

As mentioned, we have no plans to support the volcano as this time.  As this is an open source project, feel free to modify the CAD yourself to add such support.

**Comment by pasha4ur** [comment]
You are moving away from the answer to another topic.  I was asking about simulating the short volcano hotend problem, not the air flow.  Anyone understands that the thinner part of the short volcano will give more maneuvers with the location of the blowing nozzles.
