### ISSUE TITLE
Phaetus Rapido UHF support

### ISSUE THREAD

**Issue by SharkyMoto** [VoronDesign/Voron-Stealthburner#75]
Is it possible to get the Toolmount for this Hotend? It's a fair bit longer than the HF Variant, but otherwise its the same.

Could provide exact measurements if needed too!

Thanks for taking care.

**Comment by BerzerkaDurk** [comment]
The team have said that the UHF would not be supported in Stealthburner

**Comment by SharkyMoto** [comment]
oh okay, thanks for the answer :)
