### ISSUE TITLE
TOOL CARTRIDGE Screws (Page 41)

### ISSUE THREAD

**Issue by SharkyMoto** [VoronDesign/Voron-Stealthburner#77]
The manual calls for M3x12mm screws here, but when using the Rapido cartridge, those are too short (0-1 Threads engagement), 16mm works great though, so maybe worth mentioning it in the Manual.
![Screenshot_3](https://user-images.githubusercontent.com/21364981/218269390-c6d1b103-6ab4-44a3-a918-85a3a9f84e85.png)

**Comment by stahlfabrik** [comment]
Same is true for the revo voron! I came here to see if there is an issue for this. The 12mm would not engage with the thread for me.

**Comment by stahlfabrik** [comment]
Ah no - one headset I pushed to far in... the other is ok with 12mm

**Comment by massis87** [comment]
I agree, I had the exact same issue. My inserts were pushed to just proud of the service and then leveled by cooling them down pressing onto a polished granite surface, so they're completely flush, yet they would not engage. 16mm worked perfectly.

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/88
