### ISSUE TITLE
Dragon STL Issue

### ISSUE THREAD

**Issue by kogdog** [VoronDesign/Voron-Stealthburner#79]
stealthburner_printhead_dragon_front.stl has the fan in the model? 
![image](https://user-images.githubusercontent.com/125599142/219457948-2d52360d-8bba-4eb7-ac9a-0f7e4d6a64d5.png)

**Comment by BerzerkaDurk** [comment]
lol. that acts like the stator in a jet engine: it "straightens" the air passing through to reduce turbulence in the airstream and create a more laminar airflow.

If it wasn't supposed to be there, I'm sure the 3000 people who have printed these might've noticed.

Cheers.

**Comment by kogdog** [comment]
thx
