### ISSUE TITLE
Phaetus Rapido Printhead Readme/BOM lists Wrong Screw Size

### ISSUE THREAD

**Issue by SuperDodge** [VoronDesign/Voron-Stealthburner#89]
The Phaetus Rapido Printhead Readhme/BOM lists 2 M3x12 SHCS to be used to hold the two 3D printed parts together; however, those screws are not long enough to work.  M3x16 SHCS should be used.

**Comment by BerzerkaDurk** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/issues/37

**Comment by nemgrea** [comment]
duplicate, and fixed
