### ISSUE TITLE
Main Body sliced wrong

### ISSUE THREAD

**Issue by Steven2k6** [VoronDesign/Voron-Stealthburner#92]
When I slice the MainBody, the external Permiters are buggy.

![side1](https://github.com/VoronDesign/Voron-Stealthburner/assets/99575824/1f9621ab-7540-4dc9-8472-60a5681f51e6)
![side2](https://github.com/VoronDesign/Voron-Stealthburner/assets/99575824/a2238321-9f16-4407-89df-d566cc281f91)

**Comment by nemgrea** [comment]
this is a slicer issue on the user end not an issue with the STL
