### ISSUE TITLE
Is the CW2 extruder configuration not provided?

### ISSUE THREAD

**Issue by garyd9** [VoronDesign/Voron-Stealthburner#93]
The firmware directory should include a sample [extruder] configuration snippet for a suggested configuration to start with for CW2.  For example, gear_ratio and rotation_distance.  It might also be useful to include this information in the PDF manual.

**Comment by nemgrea** [comment]
theres a pull request in the trident, V2.4 and switchwire repos right now that changes the default gear ratio to 50:10 for CW2
