### ISSUE TITLE
Wrong issues link in manual

### ISSUE THREAD

**Issue by Jrribas** [VoronDesign/Voron-Stealthburner#94]
**Problem:**
"REPORTING ISSUES
Should you find an issue in the documentation or have a suggestion for an improvement please
consider opening an issue on GitHub (**https://github.com/VoronDesign/Voron-Afterburner/issues**). "

**Solution:**
Should be: https://github.com/VoronDesign/Voron-Stealthburner/issues

**Comment by agravelot** [comment]
Same at page 70 & 71

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/98
will be fixed here
